# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JiaXingZJShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JiaXingZJShop
# pod 'SnapKit'
# pod 'Then'
# pod 'Moya'
pod 'Alamofire'
pod 'HandyJSON'
pod 'Kingfisher'
pod 'SVProgressHUD'
# pod 'Reusable'
# pod 'LLCycleScrollView'
# pod 'MJRefresh'
# pod 'MBProgressHUD'
# pod 'HMSegmentedControl'
# pod 'IQKeyboardManagerSwift'
# pod 'EmptyDataSet-Swift'
# Pods for JiaxingShop
end
